// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkGoogleUser = `-- name: CheckGoogleUser :one
SELECT id, role FROM users WHERE email=$1 OR google_id=$2
`

type CheckGoogleUserParams struct {
	Email    pgtype.Text `json:"email"`
	GoogleID pgtype.Text `json:"google_id"`
}

type CheckGoogleUserRow struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) CheckGoogleUser(ctx context.Context, arg CheckGoogleUserParams) (CheckGoogleUserRow, error) {
	row := q.db.QueryRow(ctx, checkGoogleUser, arg.Email, arg.GoogleID)
	var i CheckGoogleUserRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email=$1 OR username=$2)
`

type CheckUserExistsParams struct {
	Email    pgtype.Text `json:"email"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) CheckUserExists(ctx context.Context, arg CheckUserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (name, email, google_id, avatar_url, role, username, currency)
VALUES ($1, $2, $3, $4, 'user', $5, 'INR')
RETURNING id, role
`

type CreateGoogleUserParams struct {
	Name      pgtype.Text `json:"name"`
	Email     pgtype.Text `json:"email"`
	GoogleID  pgtype.Text `json:"google_id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Username  pgtype.Text `json:"username"`
}

type CreateGoogleUserRow struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (CreateGoogleUserRow, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Name,
		arg.Email,
		arg.GoogleID,
		arg.AvatarUrl,
		arg.Username,
	)
	var i CreateGoogleUserRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, email, username, mobile, password_hash, role, currency)
VALUES ($1, $2, $3, $4, $5, 'user', 'INR')
`

type CreateUserParams struct {
	Name         pgtype.Text `json:"name"`
	Email        pgtype.Text `json:"email"`
	Username     pgtype.Text `json:"username"`
	Mobile       pgtype.Text `json:"mobile"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.Mobile,
		arg.PasswordHash,
	)
	return err
}

const getOrderStatsForUser = `-- name: GetOrderStatsForUser :one
SELECT 
    COUNT(*) FILTER (WHERE status IN ('pending', 'processing', 'submitted', 'in_progress', 'active'))::int as active_count,
    COUNT(*) FILTER (WHERE status IN ('completed', 'partial'))::int as completed_count,
    COUNT(*) FILTER (WHERE status IN ('canceled', 'failed', 'refunded'))::int as failed_count
FROM orders 
WHERE user_id = $1
`

type GetOrderStatsForUserRow struct {
	ActiveCount    int32 `json:"active_count"`
	CompletedCount int32 `json:"completed_count"`
	FailedCount    int32 `json:"failed_count"`
}

func (q *Queries) GetOrderStatsForUser(ctx context.Context, userID int32) (GetOrderStatsForUserRow, error) {
	row := q.db.QueryRow(ctx, getOrderStatsForUser, userID)
	var i GetOrderStatsForUserRow
	err := row.Scan(&i.ActiveCount, &i.CompletedCount, &i.FailedCount)
	return i, err
}

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT COALESCE(password_hash, '')::text FROM users WHERE id=$1
`

func (q *Queries) GetPasswordHash(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHash, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserDataForMe = `-- name: GetUserDataForMe :one
SELECT 
    u.id, 
    u.name, 
    COALESCE(u.username, '')::text as username, 
    u.email, 
    COALESCE(u.mobile, '')::text as mobile, 
    u.role, 
    COALESCE(u.currency, 'INR')::text as currency,
    u.created_at, 
    COALESCE(u.password_hash, '')::text as password_hash,
    COALESCE(w.balance, 0)::int as balance,
    (SELECT COUNT(*)::int FROM orders o WHERE o.user_id = u.id) as order_count,
    (SELECT COALESCE(SUM(
        CASE 
            WHEN o.status IN ('failed', 'canceled', 'refunded') THEN 0 
            ELSE o.amount_cents 
        END
    ), 0)::int FROM orders o WHERE o.user_id = u.id) as total_spend
FROM users u
LEFT JOIN wallets w ON u.id = w.user_id
WHERE u.id = $1
`

type GetUserDataForMeRow struct {
	ID           int32              `json:"id"`
	Name         pgtype.Text        `json:"name"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	Mobile       string             `json:"mobile"`
	Role         string             `json:"role"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash string             `json:"password_hash"`
	Balance      int32              `json:"balance"`
	OrderCount   int32              `json:"order_count"`
	TotalSpend   int32              `json:"total_spend"`
}

func (q *Queries) GetUserDataForMe(ctx context.Context, id int32) (GetUserDataForMeRow, error) {
	row := q.db.QueryRow(ctx, getUserDataForMe, id)
	var i GetUserDataForMeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Role,
		&i.Currency,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.Balance,
		&i.OrderCount,
		&i.TotalSpend,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, password_hash, role 
FROM users 
WHERE LOWER(email) = LOWER($1) OR LOWER(username) = LOWER($1)
`

type GetUserForLoginRow struct {
	ID           int32       `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Role         string      `json:"role"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, lower)
	var i GetUserForLoginRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Role)
	return i, err
}

const updateGoogleInfo = `-- name: UpdateGoogleInfo :exec
UPDATE users SET google_id=$1, avatar_url=$2 WHERE id=$3
`

type UpdateGoogleInfoParams struct {
	GoogleID  pgtype.Text `json:"google_id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateGoogleInfo(ctx context.Context, arg UpdateGoogleInfoParams) error {
	_, err := q.db.Exec(ctx, updateGoogleInfo, arg.GoogleID, arg.AvatarUrl, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash=$1 WHERE id=$2
`

type UpdatePasswordParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	ID           int32       `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}
