// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAdmin = `-- name: GetUserAdmin :one
SELECT 
	u.id, u.name, COALESCE(u.username, '')::text as username, u.email, COALESCE(u.mobile, '')::text as mobile, u.role, COALESCE(u.currency, 'INR')::text as currency, u.created_at,
	COALESCE(w.balance, 0)::int as balance,
	(SELECT COUNT(*)::int FROM orders o WHERE o.user_id = u.id) as order_count,
	(SELECT COALESCE(SUM(
		CASE 
			WHEN o.status IN ('failed', 'canceled', 'refunded') THEN 0 
			ELSE o.amount_cents 
		END
	), 0)::int FROM orders o WHERE o.user_id = u.id) as total_spend
FROM users u
LEFT JOIN wallets w ON u.id = w.user_id
WHERE u.id = $1
`

type GetUserAdminRow struct {
	ID         int32              `json:"id"`
	Name       pgtype.Text        `json:"name"`
	Username   string             `json:"username"`
	Email      pgtype.Text        `json:"email"`
	Mobile     string             `json:"mobile"`
	Role       string             `json:"role"`
	Currency   string             `json:"currency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Balance    int32              `json:"balance"`
	OrderCount int32              `json:"order_count"`
	TotalSpend int32              `json:"total_spend"`
}

func (q *Queries) GetUserAdmin(ctx context.Context, id int32) (GetUserAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserAdmin, id)
	var i GetUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.Role,
		&i.Currency,
		&i.CreatedAt,
		&i.Balance,
		&i.OrderCount,
		&i.TotalSpend,
	)
	return i, err
}

const getUserOrdersAdmin = `-- name: GetUserOrdersAdmin :many
SELECT id, service_id, amount_cents, status, created_at 
FROM orders 
WHERE user_id = $1 
ORDER BY created_at DESC 
LIMIT 5
`

type GetUserOrdersAdminRow struct {
	ID          int32              `json:"id"`
	ServiceID   string             `json:"service_id"`
	AmountCents int32              `json:"amount_cents"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserOrdersAdmin(ctx context.Context, userID int32) ([]GetUserOrdersAdminRow, error) {
	rows, err := q.db.Query(ctx, getUserOrdersAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrdersAdminRow
	for rows.Next() {
		var i GetUserOrdersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.AmountCents,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT u.id, u.name, u.email, u.role, COALESCE(u.api_key, '')::text as api_key, COALESCE(w.balance, 0)::int as balance
FROM users u LEFT JOIN wallets w ON u.id = w.user_id WHERE u.email = $1
`

type GetUserProfileRow struct {
	ID      int32       `json:"id"`
	Name    pgtype.Text `json:"name"`
	Email   pgtype.Text `json:"email"`
	Role    string      `json:"role"`
	ApiKey  string      `json:"api_key"`
	Balance int32       `json:"balance"`
}

func (q *Queries) GetUserProfile(ctx context.Context, email pgtype.Text) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, email)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.ApiKey,
		&i.Balance,
	)
	return i, err
}

const getUserTransactionsAdmin = `-- name: GetUserTransactionsAdmin :many
SELECT id, amount, type, description, created_at 
FROM transactions 
WHERE user_id = $1 
ORDER BY created_at DESC 
LIMIT 10
`

type GetUserTransactionsAdminRow struct {
	ID          int32              `json:"id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserTransactionsAdmin(ctx context.Context, userID pgtype.Int4) ([]GetUserTransactionsAdminRow, error) {
	rows, err := q.db.Query(ctx, getUserTransactionsAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTransactionsAdminRow
	for rows.Next() {
		var i GetUserTransactionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT 
	u.id, u.name, COALESCE(u.username, '')::text as username, u.email, COALESCE(u.mobile, '')::text as mobile, u.role, COALESCE(u.currency, 'INR')::text as currency, u.created_at,
	COALESCE(w.balance, 0)::int as balance,
	(SELECT COUNT(*)::int FROM orders o WHERE o.user_id = u.id) as order_count,
	(SELECT COALESCE(SUM(
		CASE 
			WHEN o.status IN ('failed', 'canceled', 'refunded') THEN 0 
			ELSE o.amount_cents 
		END
	), 0)::int FROM orders o WHERE o.user_id = u.id) as total_spend
FROM users u
LEFT JOIN wallets w ON u.id = w.user_id
WHERE ($3::text = '' OR u.name ILIKE '%' || $3 || '%' OR u.email ILIKE '%' || $3 || '%')
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

type GetUsersRow struct {
	ID         int32              `json:"id"`
	Name       pgtype.Text        `json:"name"`
	Username   string             `json:"username"`
	Email      pgtype.Text        `json:"email"`
	Mobile     string             `json:"mobile"`
	Role       string             `json:"role"`
	Currency   string             `json:"currency"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Balance    int32              `json:"balance"`
	OrderCount int32              `json:"order_count"`
	TotalSpend int32              `json:"total_spend"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Mobile,
			&i.Role,
			&i.Currency,
			&i.CreatedAt,
			&i.Balance,
			&i.OrderCount,
			&i.TotalSpend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users SET 
    name = COALESCE($2, name),
    mobile = COALESCE($3, mobile),
    currency = COALESCE($4, currency)
WHERE id = $1
`

type UpdateProfileParams struct {
	ID       int32       `json:"id"`
	Name     pgtype.Text `json:"name"`
	Mobile   pgtype.Text `json:"mobile"`
	Currency pgtype.Text `json:"currency"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Mobile,
		arg.Currency,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET 
    name = COALESCE($2, name),
    email = COALESCE($3, email),
    role = COALESCE($4, role),
    mobile = COALESCE($5, mobile),
    currency = COALESCE($6, currency)
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32       `json:"id"`
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	Role     pgtype.Text `json:"role"`
	Mobile   pgtype.Text `json:"mobile"`
	Currency pgtype.Text `json:"currency"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Mobile,
		arg.Currency,
	)
	return err
}
